language: cpp
compiler: gcc

before_install:
 - sudo apt-get update

install: 
 - sudo apt-get install build-essential
 - sudo apt-get install cmake
 - sudo apt-get install libopenblas-dev liblapack-dev
 - sudo apt-get install git libgtk2.0-dev pkg-config libavcodec-dev libavformat-dev libswscale-dev 
 - sudo apt-get install python-dev python-numpy libtbb2 libtbb-dev libjpeg-dev libpng-dev libtiff-dev libjasper-dev libdc1394-22-dev checkinstall
 - sudo apt-get install libboost-all-dev

before_script:
 - git clone https://github.com/Itseez/opencv.git
 - cd opencv
 - mkdir build
 - cd build
 - cmake ..
 - make -j4
 - sudo make -j4 install
 - cd ../..
 - cmake .
 - make

script:
 ./bin/SimpleCLM -f "./videos/changeLighting.wmv" -f "./videos/0188_03_021_al_pacino.avi" -f "./videos/0217_03_006_alanis_morissette.avi" -f "./videos/0244_03_004_anderson_cooper.avi" -f "./videos/0294_02_004_angelina_jolie.avi" -f "./videos/0417_02_003_bill_clinton.avi" -f "./videos/0490_03_007_bill_gates.avi" -f "./videos/0686_02_003_gloria_estefan.avi" -f "./videos/1034_03_006_jet_li.avi" -f "./videos/1192_01_006_julia_roberts.avi" -f "./videos/1461_01_021_noam_chomsky.avi" -f "./videos/1804_03_006_sylvester_stallone.avi" -f "./videos/1815_01_008_tony_blair.avi" -f "./videos/1869_03_009_victoria_beckham.avi" -f "./videos/1878_01_002_vladimir_putin.avi"
os:
 - linux
branches:
  only:
    - maintenance